### PR TITLE
Add woff2 extension to font assets, fixes #218

### LINKED ISSUE #218: rails-assets-fontawesome is missing woff2 font
Getting this error:

``` bash
http://localhost:3000/fonts/fontawesome/fonts/fontawesome-webfont.woff2?v=4.3.0
Failed to load resource: the server responded with a status of 404 (Not Found)
```

### PR DESCRIPTION
**Pull request by mtsmfm**

### CODE REVIEW

**Comment by fstybel** [comment]
:+1:

**Comment by mtsmfm** [comment]
:smile:

**Comment by sheerun** [comment]
It won't work immediately. We need to rebuild all gems..

**Comment by sheerun** [comment]
Or we need to implement selective rebuilding: #212

**Pull request merged**
