### PR TITLE
Leave only Gemfile from test-app.

### PR DESCRIPTION
**Pull request by sheerun**
And move Gemfile to test directory, where it belongs.

\cc @jandudulski @teamon

### CODE REVIEW

**Comment by porada** [comment]
IMHO, the test app should live in a separate repository.

**Comment by sheerun** [comment]
imho we don't need test app, but test Gemfile, what this commit does

**Comment by porada** [comment]
I guess that’s okay, too.

**Comment by teamon** [comment]
Gemfile is not enough, we do want to check if libs are working, especially combo packages like leaflet with css and images

**Comment by sheerun** [comment]
Gemfile should be only for e2e test. Checking if packages contain javascripts/stylesheets is already implemented in tests.

**Comment by sheerun** [comment]
@teamon @jandudulski

**Pull request closed without merging**
