### PR TITLE
Natural sorting for versions

### PR DESCRIPTION
**Pull request by syabruk**
Before:

```
jquery 1.10.0, 1.2.3, 2.0.3
```

After:

```
jquery 1.2.3, 1.10.0, 2.0.3
```

### CODE REVIEW

**Comment by sheerun** [comment]
Thanks! It's on production. We could also use some limitTo and http://binarymuse.github.io/ngInfiniteScroll/ because rendering really hangs now. If you have some time I encourage you to experiment with this :)

**Comment by sheerun** [comment]
Hmm. I pushed it without local testing, it seemed so simple, but now I'm not sure it's working: https://rails-assets.org/components

@SeTeM Could you check it one more time?

**Comment by syabruk** [comment]
You are right, now sorting is worse then before. Please wait, i'll fix my mistake.

**Comment by sheerun** [comment]
@SeTeM Maybe use Ruby / JavaScript semver libraries for comparator implementation.

**Comment by syabruk** [comment]
@sheerun oh, it was a little bit complicated:  https://github.com/SeTeM/rails-assets/commit/b479c69efa259d1ead4d533b957ccc1580df78e4

This is the best solution I've have found. It has some magic sorting from http://mottie.github.io/tablesorter/docs/example-option-textsorter-semver.html

**Comment by sheerun** [comment]
Hey. What's the progress?

**Comment by sheerun** [comment]
Nvm, closed by b9db9c8a05602df5f9bef7043620f25525fa0d74 :)

**Comment by syabruk** [comment]
@sheerun wow, you've found better semver.browser.js!

**Comment by sheerun** [comment]
it's just compiled https://npmjs.org/doc/misc/semver.html

**Comment by syabruk** [comment]
@sheerun There are 120 js errors on https://rails-assets.org/components
We've forgot, that not all libraries are using semver

**Comment by sheerun** [comment]
I've reverted everything, sorry. We need proper PR and proper testing.

**Comment by porada** [comment]
I wrote the [filter with a fallback to alphabetical sorting](https://github.com/monterail/angular-semver-sort/blob/master/src/angular-semver-sort.js) and implemented it here (via c2cb219e661969184a6d17d37f428d852f4451b4).

**Pull request merged**
