### PR TITLE
Add security note about blocks instead of global source

### PR DESCRIPTION
**Pull request by sfcgeorge**
Added initial notes to address #379

The Gemfile diff isn't very nice now, maybe you want to present it differently.

Split in small commits so you could merge just 1 mention if you think it's too ugly.

### CODE REVIEW

**Comment by sfcgeorge** [comment]
This doesn't address the inline installation instructions for specific gems. Not sure what if anything to do about that as it won't look great.

**Comment by hut8** [comment]
Wow, that was quick. 👍 I will be merging this soon.

**Comment by hut8** [comment]
Deployed to production! Thanks so much.

**Comment by sfcgeorge** [comment]
Cool :)

**Pull request merged**
