### PR TITLE
ran runbocop on app/. no semantic changes.

### PR DESCRIPTION
**Pull request by hut8**

### CODE REVIEW

**Comment by joshjordan** [comment]
@hut8 can we fix the weirdo indentation before merge?

**Comment by joshjordan** [comment]
Other than, looks very positive to me.

**Comment by joshjordan** [comment]
@hut8 what's the word on the indentation here?

**Comment by hut8** [comment]
The word is that `rubocop` isn't down with the `extends self` stuff. https://github.com/bbatsov/ruby-style-guide#module-function

Will fix nowish.

**Comment by hut8** [comment]
@joshjordan done. Your test suite saved the day!

**Comment by hut8** [comment]
@joshjordan oops one more. 1 sec.

**Comment by joshjordan** [comment]
Nice! Merge it when ready.

**Pull request merged**
