### PR TITLE
Adding .cur (cursor file) as an image extension

### PR DESCRIPTION
**Pull request by golmansax**
The `signature-pad` Bower package uses a `.cur` file, so I would like to add that extension.  I thought the best place to put this was in `images` because the `.cur` file is a picture of a cursor.

### CODE REVIEW

**Comment by sheerun** [comment]
Tests are failing, but for different reason. Thanks for PR.

**Comment by golmansax** [comment]
Thanks for the quick response.  How would I refresh the Gem so that the gem reflects the changes from this pull request?  I tried doing a `gem uninstall rails-assets-signature-pad` and `bundle install` from my Rails project and the gem is still missing the `.cur` file.

**Comment by sheerun** [comment]
Unfortunately such change require us to rebuild all gems. I'll notify you when the next major rebuild will be done (I want to batch changes).

**Comment by golmansax** [comment]
Great, thanks!

On Mon, Feb 17, 2014 at 11:16 AM, Adam Stankiewicz <notifications@github.com

**Comment by sheerun** [comment]
For you the only option to now is to copy .cur files to vendor/assets/images by hand

**Comment by golmansax** [comment]
Yeah I put that in.  Thanks for the note.

**Pull request merged**
