### PR TITLE
support css syntax without a space: background-image:url(...)

### PR DESCRIPTION
**Pull request by elado**
- used to remove the colon before
- converted quote lookup with a backreference

### CODE REVIEW

**Comment by sheerun** [comment]
Hey. Could you also include some tests in builder_spec ?

**Comment by ai** [comment]
@sheerun any updates? Can I somehow help with this issue?

**Comment by ai** [comment]
I try to add specs in @elado branch, but get error, when I try to run test:

```
undefined method `raven_dsn' for {}:Figaro::Env` 
```

Any ideas, how to fix it (I use Linux if it is vendor specific)?

**Comment by sheerun** [comment]
@ai Thanks for helping, I'll take care of this issue.

Such changes require full rebuild of all gems so I'd like to batch them.

I think we can deploy this along #128

**Comment by sheerun** [comment]
@ai Ensure you copy application.sample.yml to application.yml, btw.

**Comment by ai** [comment]
I add tests =^_^= #129

**Comment by ai** [comment]
When you run rebuild? :) (I want to clean a lot of mess from `vendor/` in one of us project)

**Comment by sheerun** [comment]
OK, finally fixed and deployed. Thank for commit and issue @elado Thanks for helping @ai

**Comment by sheerun** [comment]
If you still encounter error:

```
gem list | grep rails-assets | cut -d ' ' -f 1 | xargs gem uninstall -aIx
bundle install
```

**Pull request closed without merging**
