### PR TITLE
Add specs for component model + fixes

### PR DESCRIPTION
**Pull request by sheerun**
I'll be putting here specs I write.

Note 1: All changes to models are due to failing tests I wrote.
Note 2: I am not comfortable with minispec, so I replaced it with rspec (currently there are no unit tests anyway).

### CODE REVIEW

**Comment by teamon** [comment]
Please wait for a while, I have some pending changes to builder classes (+1
for rspec, minitest turns out to suck a lot)

**Comment by sheerun** [comment]
yeah, now I know. I wrote this yesterday.

**Comment by sheerun** [comment]
I'll rebase if necessary.

**Comment by teamon** [comment]
You're doing that for your own risk, I warned you :)

**Comment by sheerun** [comment]
Don't worry, you won't merge this until all tests pass.

**Comment by sheerun** [comment]
@teamon Please merge this to master so I can use specs in other branches.

**Pull request merged**
